"""Build docs/data/soil_data.js (the dashboard, served by GitHub Pages) from the corrected summary workbook.

Run from the repository root, after scripts/build_summary_xlsx.py:
    python scripts/build_data.py

All QA/QC corrections, the links to the raw KD2 Pro heat-pulse records and the Rosetta
van Genuchten parameters already live in kansas_mesonet_soil_database_summary_2026.xlsx.
"""

import json
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_summary_xlsx import OUT as WORKBOOK, STATES  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'docs' / 'data' / 'soil_data.js'
KEY = ['station_name', 'ring_number']
CM_PER_KPA = 10.197  # cm of water per kPa

# Measured on only one core of each pair; shared with the paired core at the same depth.
PAIRED = ['sand', 'silt', 'clay', 'L_dry', 'a_dry', 'b_dry', 'L_wet', 'a_wet', 'b_wet',
          'total_N', 'total_C', 'Ca', 'Mg', 'Na', 'OM', 'P', 'pH', 'pH_buffer', 'K_ppm']


def clean(v, nd=4):
    """JSON-safe rounded value."""
    if v is None or (isinstance(v, float) and np.isnan(v)) or v is pd.NaT:
        return None
    if isinstance(v, (int, np.integer)):
        return int(v)
    if isinstance(v, (float, np.floating)):
        return round(float(v), nd)
    return v


def main():
    x = pd.ExcelFile(WORKBOOK)
    G, H, P = (x.parse(s) for s in ['general_properties', 'hydraulic_properties', 'heat_pulse_timeseries'])
    for c in PAIRED:
        G[c] = G.groupby(['station_name', 'nominal_depth'])[c].transform(lambda s: s.fillna(s.mean()))
    df = G.merge(H.drop(columns=[c for c in H.columns if c in G.columns and c not in KEY]), on=KEY, how='left')

    state_id = {label: sid for sid, label, _, _ in STATES}
    temp_cols = [c for c in P.columns if c.startswith('temp_') and c.endswith('s')]
    P['core_idx'] = P.merge(df.reset_index()[KEY + ['index']], on=KEY, how='left')['index']

    cores = []
    for i, r in df.iterrows():
        cores.append({
            'id': i, 'station': r.station_name, 'county': r.county,
            'lat': clean(r.latitude, 5), 'lon': clean(r.longitude, 5),
            'ring': int(r.ring_number), 'core': int(r.core_number),
            'depth': int(r.nominal_depth), 'top': clean(r.top_depth), 'bottom': clean(r.bottom_depth),
            'date': pd.Timestamp(r.sampling_date).strftime('%Y-%m-%d') if pd.notna(r.sampling_date) else None,
            'texture': r.textural_class,
            'sand': clean(r.sand, 2), 'silt': clean(r.silt, 2), 'clay': clean(r.clay, 2),
            'bd': clean(r.bulk_density), 'pd': clean(r.particle_density), 'por': clean(r.porosity),
            'L_dry': clean(r.L_dry, 2), 'a_dry': clean(r.a_dry, 2), 'b_dry': clean(r.b_dry, 2),
            'L_wet': clean(r.L_wet, 2), 'a_wet': clean(r.a_wet, 2), 'b_wet': clean(r.b_wet, 2),
            'N': clean(r.total_N), 'C': clean(r.total_C), 'OM': clean(r.OM, 2), 'pH': clean(r.pH, 2),
            'pHBuf': clean(r.pH_buffer, 2), 'Ca': clean(r.Ca, 1), 'Mg': clean(r.Mg, 1), 'Na': clean(r.Na, 1),
            'Kppm': clean(r.K_ppm, 1), 'P': clean(r.P, 1),
            'vwc_field': clean(r.vwc_field), 'vwc_sat': clean(r.vwc_sat), 'vwc_2kPa': clean(r.vwc_2kPa),
            'vwc_5kPa': clean(r.vwc_5kPa), 'vwc_10kPa': clean(r.vwc_10kPa), 'vwc_33kPa': clean(r.vwc_33kPa),
            'vwc_70kPa': clean(r.vwc_70kPa), 'vwc_1500kPa': clean(r.vwc_1500kPa),
            'ksat': clean(r.Ksat_cm_per_hr), 'ksat_method': clean(r.Ksat_method),
            # Rosetta van Genuchten; α converted from cm⁻¹ to kPa⁻¹
            'vg_tr': clean(r.vg_theta_res), 'vg_ts': clean(r.vg_theta_sat),
            'vg_alpha': clean(r.vg_alpha_per_cm * CM_PER_KPA, 5), 'vg_n': clean(r.vg_n),
            'vg_model': clean(r.rosetta_model),
        })

    meas = []
    for r in P.itertuples():
        # rt: read time (min); the 60 readings are evenly spaced over it, heater on for the first half
        meas.append({
            'core': int(r.core_idx), 'state': state_id[r.water_state],
            'k': clean(r.thermal_cond, 3), 'c': clean(r.heat_capacity, 3), 'd': clean(r.diffusivity, 3),
            'theta': clean(r.vwc), 'match': r.raw_link, 't0': clean(r.initial_temp, 2), 'err': clean(r.fit_error),
            'power': clean(r.heater_power_W_per_m, 2), 'rt': clean(r.read_time_min),
            'time': clean(r.measurement_datetime) if isinstance(r.measurement_datetime, str) else None,
            'temps': [round(float(getattr(r, c)), 3) for c in temp_cols],
        })
    meas.sort(key=lambda m: (m['core'], [s[0] for s in STATES].index(m['state'])))

    data = {'states': [{'id': s[0], 'label': s[1], 'moisture': s[2]} for s in STATES],
            'cores': cores, 'measurements': meas}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('// Generated by scripts/build_data.py. Do not edit by hand.\nwindow.SOIL_DATA = '
                   + json.dumps(data, separators=(',', ':'), ensure_ascii=False) + ';\n', encoding='utf-8')
    print(f'{len(cores)} cores, {len(meas)} heat-pulse measurements from {WORKBOOK.name}')
    print(f'Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1e6:.2f} MB)')
    # Copy of the workbook for the dashboard's download link (keeps the dashboard folder self-contained)
    shutil.copyfile(WORKBOOK, OUT.parent / WORKBOOK.name)
    print(f'Copied {WORKBOOK.name} to {OUT.parent.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
