"""Cut the soil core photo atlas into Deep Zoom (DZI) tiles for the dashboard's zoomable viewer.

Run from the repository root:
    python scripts/build_atlas_tiles.py

Reads docs/data/kansas_mesonet_soil_atlas_black.jpg (12,500 x 9,670 px) and writes
docs/data/atlas_files/{level}/{col}_{row}.jpg plus docs/data/atlas.js, which holds the image
size, tile layout and the bounding box of each station panel (used to zoom to a station).
A full-size decode of the atlas needs ~0.5 GB of memory, which browsers (phones especially)
handle poorly; tiles load only what is on screen.
"""

import json
import math
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'docs' / 'data'
SRC = DATA / 'kansas_mesonet_soil_atlas_black.jpg'
TILES = DATA / 'atlas_files'
OUT_JS = DATA / 'atlas.js'
TILE, OVERLAP, QUALITY = 512, 1, 85

# Station panels in reading order (left to right, top to bottom), as laid out in the atlas
STATIONS = ['Butler', 'Cherokee', 'Cheyenne', 'Colby', 'Elmdale 1SE',
            'Garden City', 'Harper', 'Hays', 'Hodgeman', 'Jewell',
            'Lake City', 'Lakin', 'Lane', 'Leoti', 'Meade',
            'Miami', 'Moscow 10NW', 'Ottawa 2SE', 'Overbrook', 'Parsons',
            'Richfield', 'Rossville 2SE', 'Satanta', 'Sedan', 'Silver Lake 4E',
            'Spearville', 'Tribune', 'Viola', 'Woodson']


def line_groups(idx):
    """Collapse consecutive pixel indices into (start, end) runs."""
    out, start, prev = [], idx[0], idx[0]
    for i in idx[1:]:
        if i > prev + 2:
            out.append((start, prev))
            start = i
        prev = i
    out.append((start, prev))
    return out


def station_boxes(img):
    """Find the thin gray panel borders on a downscaled copy; return full-size [x, y, w, h] per station."""
    W, H = img.size
    scale = W / 2600
    small = np.asarray(img.resize((2600, round(H / scale)), Image.BILINEAR).convert('L')).astype(int)
    border = (small > 45) & (small < 140)
    rows = line_groups(np.flatnonzero(border.sum(1) > small.shape[1] * 0.55))
    cols = line_groups(np.flatnonzero(border.sum(0) > small.shape[0] * 0.5))
    assert len(rows) % 2 == 0 and len(cols) % 2 == 0, (rows, cols)
    row_spans = [(rows[i][0], rows[i + 1][1]) for i in range(0, len(rows), 2)]
    col_spans = [(cols[i][0], cols[i + 1][1]) for i in range(0, len(cols), 2)]
    gap = row_spans[1][0] - row_spans[0][1]            # space between panels holds the station title
    cells = [(c, r) for r in row_spans for c in col_spans]
    assert len(cells) >= len(STATIONS), f'{len(cells)} panels detected for {len(STATIONS)} stations'
    boxes = {}
    for name, ((x0, x1), (y0, y1)) in zip(STATIONS, cells):
        top = y0 - 0.7 * gap                            # include the title above the panel
        boxes[name] = [round(v * scale) for v in (x0, top, x1 - x0, y1 - top)]
    return boxes


def write_tiles(img):
    W, H = img.size
    max_level = math.ceil(math.log2(max(W, H)))
    if TILES.exists():
        shutil.rmtree(TILES)
    level_img, n = img, 0
    for level in range(max_level, -1, -1):
        w, h = level_img.size
        folder = TILES / str(level)
        folder.mkdir(parents=True)
        for col in range(math.ceil(w / TILE)):
            for row in range(math.ceil(h / TILE)):
                x0 = max(col * TILE - OVERLAP, 0)
                y0 = max(row * TILE - OVERLAP, 0)
                x1 = min((col + 1) * TILE + OVERLAP, w)
                y1 = min((row + 1) * TILE + OVERLAP, h)
                level_img.crop((x0, y0, x1, y1)).save(folder / f'{col}_{row}.jpg', quality=QUALITY)
                n += 1
        level_img = level_img.resize((max(1, math.ceil(w / 2)), max(1, math.ceil(h / 2))), Image.LANCZOS)
    return n


def main():
    img = Image.open(SRC).convert('RGB')
    boxes = station_boxes(img)
    n = write_tiles(img)
    atlas = {
        'width': img.size[0], 'height': img.size[1], 'tileSize': TILE, 'overlap': OVERLAP, 'format': 'jpg',
        'tiles': 'data/atlas_files/', 'preview': 'data/kansas_mesonet_soil_atlas_black_preview.jpg',
        'full': 'data/kansas_mesonet_soil_atlas_black.jpg', 'fullMB': round(SRC.stat().st_size / 1e6),
        'stations': boxes,
    }
    OUT_JS.write_text('// Generated by scripts/build_atlas_tiles.py. Do not edit by hand.\nwindow.ATLAS = '
                      + json.dumps(atlas, ensure_ascii=False) + ';\n', encoding='utf-8')
    size = sum(f.stat().st_size for f in TILES.rglob('*.jpg')) / 1e6
    print(f'{n} tiles ({size:.1f} MB) in {TILES.relative_to(ROOT)}; {len(boxes)} station panels in {OUT_JS.name}')


if __name__ == '__main__':
    main()
